[package]
name = "carlca_rs"
version = "0.1.0"
edition = "2021"

[dependencies]
yew = { version = "0.21.0", features = ["csr", "hydration", "ssr"] }
stylist = { version = "0.13.0", features = ["yew", "parser"] }
web-sys = "0.3.69"
gloo = "0.11.0"
serde = "1.0.197"
serde_json = "1.0.114"
